version: 1.0.0 ci-{build}
os: Visual Studio 2017

configuration:
  - Release

shallow_clone: false

build:
  project: IVN.sln
platform: Win32

artifacts:
  - path: Installer\IVNetwork-*.exe
  - path: Installer\IVNetworkServer-*.exe
  - path: Installer\debugfiles.zip
    name: PDB files
    type: zip

after_build:
  - cd Installer
  - build-client.bat
  - build-server.bat
  - 7z a debugfiles.zip %APPVEYOR_BUILD_FOLDER%\Build\Release\*.pdb
